# Note: If changed, don't forget to update other files in the project that hard
# coded the URLs from this file

- op: replace
  path: /spec/rules/0/host
  value: renovate--pypi-requests-vulnerability---tickerbell.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/1/host
  value: renovate--pypi-requests-vulnerability---wallstreetnow.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/2/host
  value: renovate--pypi-requests-vulnerability---supernews.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/3/host
  value: renovate--pypi-requests-vulnerability---wallstreetnow-co.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/4/host
  value: renovate--pypi-requests-vulnerability---super-news.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/5/host
  value: renovate--pypi-requests-vulnerability---projectpluto.auto-branch-pushes.ppluto-main.ppluto.dev
