kind: Rollout
apiVersion: argoproj.io/v1alpha1
metadata:
  name: ppluto-main
spec:
  selector:
    matchLabels:
      app: ppluto-main
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: ppluto-main
    spec:
      terminationGracePeriodSeconds: 1800 # https://jenakim47.tistory.com/80
      containers:
        - name: ppluto-main--prod-client
          image: registry.gitlab.com/ppluto-dev/ppluto-main/prod-client:4c0d213d3d82c73dfa7c2b2f9c4530fe6adbe803d60739d8267acea582bbc96f
          ports:
            - containerPort: 8003
            - containerPort: 8004
            - containerPort: 8005
          resources:
            # requests:
            #   cpu: 100m
            #   memory: 10Mi
            limits:
              cpu: 200m
              memory: 100Mi
              ephemeral-storage: 1Gi
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 1800"]
        - name: ppluto-main--prod-client-tickerbell
          image: registry.gitlab.com/ppluto-dev/ppluto-main/prod-client-tickerbell:f7c8d6b1129eb1fbf393aac2691cd6a73af758b99291bd993b1e458c245ba618
          ports:
            - containerPort: 5080
            - containerPort: 5095
          readinessProbe:
            httpGet:
              port: 5080
              path: /
          livenessProbe:
            httpGet:
              port: 5080
              path: /
          resources:
            # requests:
            #   cpu: 200m
            #   memory: 500Mi
            limits:
              cpu: 500m
              memory: 3Gi
              ephemeral-storage: 1Gi
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 1800"]
        - name: ppluto-main--prod-server
          image: registry.gitlab.com/ppluto-dev/ppluto-main/prod-server:ce98642f4344cdffa71ff42d75970aae9b85ada70c41a036fef3609c8376bbea
          env:
            - name: PPLUTO_SERVER_ARG_SERVER
              value: api-server
          ports:
            - containerPort: 81
            - containerPort: 82
            - containerPort: 83
            - containerPort: 84
          readinessProbe:
            # TODO: Implement gRPC health check instead. https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#probe-check-methods
            tcpSocket:
              port: 82
          # TODO: Enable `livenessProbe`.  Temporarily disabled to debug container crash issue.
          # livenessProbe:
          #   tcpSocket:
          #     port: 82
          resources:
            # requests:
            #   cpu: 500m
            #   memory: 1Gi
            #   ephemeral-storage: 3Gi
            limits:
              cpu: 1000m
              memory: 3Gi
              ephemeral-storage: 5Gi
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 1800"]
      imagePullSecrets:
        - name: gitlab-container-registry
  strategy:
    blueGreen:
      activeService: ppluto-main-service-active
      previewService: ppluto-main-service-preview
      autoPromotionEnabled: true
