THETERMINALX_COM_DOMAIN: theterminalx.com
WWW_PROJECTPLUTO_CO_DOMAIN: www.projectpluto.co
OPENEMBEDDING_COM_DOMAIN: openembedding.com
TERMINAL_SUPERSEARCHX_COM_DOMAIN: terminal.supersearchx.com
APP_TERMINAL_X_AI_SUBDOMAIN: app.terminal-x.ai

PPLUTO_MAIN_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_MISC_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_WSRV_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_CRAWLING_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_WORKER_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_TEMPORAL_WORKER_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_TEMPORAL_WORKER_MAIN_HIGH_PRIORITY_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_TEMPORAL_WORKER_MAIN_MEDIUM_PRIORITY_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_TEMPORAL_WORKER_MAIN_TEST_DEPLOYMENT_REPLICAS: 0

INGRESS_TYPE: EKS
