# Note: If changed, don't forget to update other files in the project that hard
# coded the URLs from this file

- op: replace
  path: /spec/rules/0/host
  value: yansfil--node-toolbar-linebreak---tickerbell.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/1/host
  value: yansfil--node-toolbar-linebreak---gaia.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/2/host
  value: yansfil--node-toolbar-linebreak---projectpluto.auto-branch-pushes.ppluto-main.ppluto.dev
