TICKERBELL_AI_DOMAIN: tickerbell.ai
WALLSTREET_NOW_COM_DOMAIN: wallstreet-now.com
SUPERNEWS_IO_DOMAIN: supernews.io
WALLSTREETNOW_CO_DOMAIN: wallstreetnow.co
SUPER_NEWS_DOMAIN: super.news
SUPERSEARCHX_COM_DOMAIN: supersearchx.com
BLACKSWANPOST_COM_DOMAIN: blackswanpost.com
WWW_PROJECTPLUTO_CO_DOMAIN: www.projectpluto.co
OPENEMBEDDING_COM_DOMAIN: openembedding.com
TERMINAL_SUPERSEARCHX_COM_DOMAIN: terminal.supersearchx.com

PPLUTO_MAIN_DEPLOYMENT_REPLICAS: 5
PPLUTO_MAIN_MISC_DEPLOYMENT_REPLICAS: 1
PPLUTO_MAIN_WSRV_DEPLOYMENT_REPLICAS: 3
PPLUTO_MAIN_CRAWLING_DEPLOYMENT_REPLICAS: 1
PPLUTO_MAIN_WORKER_DEPLOYMENT_REPLICAS: 3

INGRESS_TYPE: GKE
