# Note: If changed, don't forget to update other files in the project that hard
# coded the URLs from this file

- op: replace
  path: /spec/rules/0/host
  value: sg--fix-favi---tickerbell.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/1/host
  value: sg--fix-favi---wallstreetnow.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/2/host
  value: sg--fix-favi---supernews.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/3/host
  value: sg--fix-favi---wallstreetnow-co.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/4/host
  value: sg--fix-favi---super-news.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/5/host
  value: sg--fix-favi---gaia.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/6/host
  value: sg--fix-favi---projectpluto.auto-branch-pushes.ppluto-main.ppluto.dev
