# Note: If changed, don't forget to update other files in the project that hard
# coded the URLs from this file

- op: replace
  path: /spec/rules/0/host
  value: sg--fix-wsj-crawling---tickerbell.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/1/host
  value: sg--fix-wsj-crawling---wallstreetnow.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/2/host
  value: sg--fix-wsj-crawling---supernews.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/3/host
  value: sg--fix-wsj-crawling---wallstreetnow-co.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/4/host
  value: sg--fix-wsj-crawling---super-news.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/5/host
  value: sg--fix-wsj-crawling---projectpluto.auto-branch-pushes.ppluto-main.ppluto.dev
