# Note: If changed, don't forget to update other files in the project that hard
# coded the URLs from this file

- op: replace
  path: /spec/rules/0/host
  value: kkimdev--hompage-background---tickerbell.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/1/host
  value: kkimdev--hompage-background---deadrabbit.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/2/host
  value: kkimdev--hompage-background---gaia.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/3/host
  value: kkimdev--hompage-background---projectpluto.auto-branch-pushes.ppluto-main.ppluto.dev
