- op: replace
  path: /spec/rules/0/host
  value: tickerbell.ai
- op: replace
  path: /spec/rules/1/host
  value: wallstreet-now.com
- op: replace
  path: /spec/rules/2/host
  value: supernews.io
- op: replace
  path: /spec/rules/3/host
  value: wallstreetnow.co
- op: replace
  path: /spec/rules/4/host
  value: super.news
- op: replace
  path: /spec/rules/5/host
  value: supersearchx.com
- op: replace
  path: /spec/rules/6/host
  value: www.projectpluto.co
