kind: Deployment
apiVersion: apps/v1
metadata:
  name: ppluto-main2
spec:
  selector:
    matchLabels:
      app: ppluto-main2
  replicas: 1
  template:
    metadata:
      labels:
        app: ppluto-main2
    spec:
      containers:
        - name: ppluto-main--prod-client
          image: registry.gitlab.com/ppluto-dev/ppluto-main/prod-client:UNSPECIFIED
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 4
            periodSeconds: 10
        - name: ppluto-main--prod-server
          image: registry.gitlab.com/ppluto-dev/ppluto-main/prod-server:UNSPECIFIED
          ports:
            - containerPort: 81
            - containerPort: 82
          readinessProbe:
            tcpSocket:
              port: 82
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: gitlab-container-registry
