kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - deployment-crawling.yaml
images:
  - name: registry.gitlab.com/ppluto-dev/ppluto-main/prod-client
    newTag: d845d9759707aefa52960ebe052a8780e290350a54c07a863b4688c94f8dd663
  - name: registry.gitlab.com/ppluto-dev/ppluto-main/prod-server
    newTag: 5cbb7ac5a9b239a96bec06efc23589e3d8055f4f5e0f5744e4f839ce972b1888
