# Note: If changed, don't forget to update other files in the project that hard
# coded the URLs from this file

- op: replace
  path: /spec/rules/0/host
  value: kkimdev--ddd-url---tickerbell.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/1/host
  value: kkimdev--ddd-url---deadrabbit.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/2/host
  value: kkimdev--ddd-url---gaia.auto-branch-pushes.ppluto-main.ppluto.dev
