# Note: If changed, don't forget to update other files in the project that hard
# coded the URLs from this file

THETERMINALX_COM_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---theterminalx.auto-branch-pushes.ppluto-main.ppluto.dev
WWW_PROJECTPLUTO_CO_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---projectpluto.auto-branch-pushes.ppluto-main.ppluto.dev
OPENEMBEDDING_COM_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---gaia.auto-branch-pushes.ppluto-main.ppluto.dev
TERMINAL_SUPERSEARCHX_COM_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---terminal-supersearchx-com.auto-branch-pushes.ppluto-main.ppluto.dev

PPLUTO_MAIN_DEPLOYMENT_REPLICAS: 1
PPLUTO_MAIN_MISC_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_WSRV_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_CRAWLING_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_WORKER_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_TEMPORAL_WORKER_DEPLOYMENT_REPLICAS: 0

INGRESS_TYPE: GKE
