# Note: If changed, don't forget to update other files in the project that hard
# coded the URLs from this file

TICKERBELL_AI_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---tickerbell.auto-branch-pushes.ppluto-main.ppluto.dev
WALLSTREET_NOW_COM_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---wallstreetnow.auto-branch-pushes.ppluto-main.ppluto.dev
SUPERNEWS_IO_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---supernews.auto-branch-pushes.ppluto-main.ppluto.dev
WALLSTREETNOW_CO_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---wallstreetnow-co.auto-branch-pushes.ppluto-main.ppluto.dev
SUPER_NEWS_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---super-news.auto-branch-pushes.ppluto-main.ppluto.dev
SUPERSEARCHX_COM_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---supersearchx.auto-branch-pushes.ppluto-main.ppluto.dev
WWW_PROJECTPLUTO_CO_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---projectpluto.auto-branch-pushes.ppluto-main.ppluto.dev
OPENEMBEDDING_COM_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---gaia.auto-branch-pushes.ppluto-main.ppluto.dev
TERMINAL_SUPERSEARCHX_COM_DOMAIN: $SUBDOMAIN_FROM_BRANCH_NAME---terminal-supersearchx-com.auto-branch-pushes.ppluto-main.ppluto.dev

PPLUTO_MAIN_DEPLOYMENT_REPLICAS: 1
PPLUTO_MAIN_MISC_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_WSRV_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_CRAWLING_DEPLOYMENT_REPLICAS: 0
PPLUTO_MAIN_WORKER_DEPLOYMENT_REPLICAS: 0
INGRESS_TYPE: GKE
