apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patches/deployment.yaml
  - path: patches/ingress.yaml
    target:
      kind: Ingress
      name: ingress

  # Crawling pods
  - target:
      kind: Deployment
      name: ppluto-main-crawling-marketwatch
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-summarize
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-thestreet
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-tipranks
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-vectorizer
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-bloomberg
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-cnbc
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-financial-times
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-trading-view
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-barrons
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-wsj
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-benzinga
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-newsletter
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-create-custom-data-document
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-create-news-contents
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-update-vector-status-outdated
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: ppluto-main-crawling-create-article-summary
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
