# Note: If changed, don't forget to update other files in the project that hard
# coded the URLs from this file

- op: replace
  path: /spec/rules/0/host
  value: yansfil--fix-deployment-run-modal---tickerbell.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/1/host
  value: yansfil--fix-deployment-run-modal---wallstreetnow.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/2/host
  value: yansfil--fix-deployment-run-modal---supernews.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/3/host
  value: yansfil--fix-deployment-run-modal---wallstreetnow-co.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/4/host
  value: yansfil--fix-deployment-run-modal---super-news.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/5/host
  value: yansfil--fix-deployment-run-modal---gaia.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/6/host
  value: yansfil--fix-deployment-run-modal---projectpluto.auto-branch-pushes.ppluto-main.ppluto.dev
