kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - deployment-crawling.yaml
  - deployment-misc.yaml
images:
  - name: registry.gitlab.com/ppluto-dev/ppluto-main/prod-client
    newTag: 6fc5ea11068b52fa13b45a47e649d050ded01943d54cb1de9efb936884870fe3
  - name: registry.gitlab.com/ppluto-dev/ppluto-main/prod-server
    newTag: cd174d95c418baa28726108ed86cbecf2a8ba036909edb21627aec2e621e4e33
  - name: registry.gitlab.com/ppluto-dev/ppluto-main/prod-client-tickerbell
    newTag: 07d4e85194d17d9f312822d540b773c4b80350486419ac06859836a9a40dc24c
