# Note: If changed, don't forget to update other files in the project that hard
# coded the URLs from this file

- op: replace
  path: /spec/rules/0/host
  value: kkimdev--crawling-fix-5---tickerbell.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/1/host
  value: kkimdev--crawling-fix-5---wallstreetnow.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/2/host
  value: kkimdev--crawling-fix-5---supernews.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/3/host
  value: kkimdev--crawling-fix-5---wallstreetnow-co.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/4/host
  value: kkimdev--crawling-fix-5---super-news.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/5/host
  value: kkimdev--crawling-fix-5---gaia.auto-branch-pushes.ppluto-main.ppluto.dev
- op: replace
  path: /spec/rules/6/host
  value: kkimdev--crawling-fix-5---projectpluto.auto-branch-pushes.ppluto-main.ppluto.dev
