kind: Deployment
apiVersion: apps/v1
metadata:
  name: ppluto-main-prerender
spec:
  selector:
    matchLabels:
      app: ppluto-main-prerender
  replicas: 1 # TODO: More replicas for prod?
  template:
    metadata:
      labels:
        app: ppluto-main-prerender
    spec:
      terminationGracePeriodSeconds: 60 # https://jenakim47.tistory.com/80
      containers:
        - name: ppluto-main--prod-prerender
          image: registry.gitlab.com/ppluto-dev/ppluto-main/prod-server:UNSPECIFIED
          env:
            - name: PPLUTO_SERVER
              value: prerender
          ports:
            - containerPort: 5088
          readinessProbe:
            # TODO: We should also check the status code
            tcpSocket:
              port: 5088
          # TODO: Enable `livenessProbe`.
          # livenessProbe:
          #   tcpSocket:
          #     port: 5088
          resources:
            limits:
              ephemeral-storage: "2Gi"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 60"]

      imagePullSecrets:
        - name: gitlab-container-registry
